### PR TITLE
Rebuilding for Titanium SDK 6.0.0+

### PR DESCRIPTION
**Pull request by gimdongwoo**

### CODE REVIEW

**Comment by Qonstrukt** [comment]
I've merged m1ga's PR since it contains only the minimum necessary changes. And I see a lot of unnecessary(?) added files in your PR. I've also made m1ga collaborator, so he can have a look at your PR if necessary.

**Comment by gimdongwoo** [comment]
Oh, I'm sorry.
I will try again with minimum change.
I love this module.
Thank you.

**Comment by m1ga** [comment]
@Qonstrukt thanks!

**Comment by m1ga** [comment]
I think I can close this since it's working with 6 already. Thanks anyway

**Pull request closed without merging**
